const TIMER = {
  INCREMENT_BREAK: "INCREMENT_BREAK",
  INCREMENT_SESSION: "INCREMENT_SESSION",
  DECREMENT_BREAK: "DECREMENT_BREAK",
  DECREMENT_SESSION: "DECREMENT_SESSION",
  START_STOP: "START_STOP",
  RESET_TIME: "RESET_TIME",
  RESET_TIMER: "RESET_TIMER",
  UPDATE_TIME: "UPDATE_TIME",
  TOGGLE_TIMER_TYPE: "TOGGLE_TIMER_TYPE"
};

export default TIMER;
