const TIMER = {
  INCREMENT_BREAK: "INCREMENT_BREAK",
  INCREMENT_SESSION: "INCREMENT_SESSION",
  DECREMENT_BREAK: "DECREMENT_BREAK",
  DECREMENT_SESSION: "DECREMENT_SESSION"
};

export default TIMER;
