const TIMER = {
  INCREMENT_BREAK: "INCREMENT_BREAK",
  INCREMENT_SESSION: "INCREMENT_SESSION",
  DECREMENT_BREAK: "DECREMENT_BREAK",
  DECREMENT_SESSION: "DECREMENT_SESSION",
  START_STOP: "START_STOP",
  RESET: "RESET",
  UPDATE_TIME: "UPDATE_TIME"
};

export default TIMER;
